<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AI_OOR" Id="{52422886-8109-46f9-8c8c-d3fd02d10c9a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION AI_OOR : BOOL
VAR_INPUT
	Status:WORD;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[// calculate whether the status for an analog input is indicating an error
// the error bit is the 7th bit of the status word
// access to bits is base 0, so the 7th bit is accessed with index 6

AI_OOR:= Status.6;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>