<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{597f0add-bcb3-437c-8260-9c2a3e1283b3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	PDUs:AllPDUs;
	CRAHs: AllCRAHs;
	IOStatus: All_IO;
	RTUStatus: AllRTUStat;
	CACs: AllCACs;
	IDF: AlllDF;
	OtherDIs: AllOtherDIs;
	EnergyMeters: AllEMeters;
	SystemTimeCall: SystemTime;
	ModbusComms: Modbus_RTU;
	
	bEmpryVar: BOOL;
	fTestFloat: REAL;
	bTestBool: BOOL;
	wTestWord: WORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
ModbusComms();

CRAHs();
CACs();
PDUs();
IDF();
OtherDIs();
EnergyMeters();

IOStatus();
RTUStatus();

SystemTimeCall();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>