<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{597f0add-bcb3-437c-8260-9c2a3e1283b3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	IOStatus: All_IO;
	ModbusComms: Modbus_RTU;
	CRAHs: AllCRAHs;
	CACs: AllCACs;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
IOStatus();
ModbusComms();

CRAHs();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>